// frontend/src/components/InsertPosts.vue
<template>
    <div id="InsertPosts">
        <b-form @submit="onSubmit" @reset="onReset" v-if="show">
            <b-form-group id="input-group-1" label="제목:" label-for="input-1" description="제목을 작성해주세요.">
                <b-form-input
                        id="title"
                        v-model="form.title"
                        type="text"
                        required
                        placeholder="Enter title"></b-form-input>
            </b-form-group>

            <b-form-group id="input-group-2" label="작성자:" label-for="input-2">
                <b-form-input
                        id="author"
                        v-model="form.author"
                        placeholder="Enter author"></b-form-input>
            </b-form-group>

            <b-form-group id="input-group-3" label="내용:" label-for="input-3">
                <b-form-input
                        id="content"
                        v-model="form.content"
                        placeholder="Enter author"></b-form-input>
            </b-form-group>

            <b-button type="submit" variant="primary">글등록</b-button>
            <b-button type="reset" variant="danger">초기화</b-button>

        </b-form>

        <b-card class="mt-3" header="Form Data Result">
            <pre class="m-0">{{ form }}</pre>
        </b-card>
    </div>
</template>

<script>
    export default {
        name: "InsertPosts",
        data() {
            return {
                form: {title: '', author: '', content: ''},
                show: true
            }
        },
        methods: {
            onSubmit(evt) {
                evt.preventDefault();

                this.$http.post('/api/insert',
                    JSON.stringify(this.form),
                    {headers: {'Content-Type': 'application/json;charset=UTF-8'}}
                ).then(function (response) {
                    if(response.status===200){
                        alert(response.status);
                        location.reload(true);
                    }
                }).catch(function (error) {
                    alert(error);
                })
            },
            onReset(evt) {
                evt.preventDefault();
                this.form.title = '';
                this.form.author = '';
                this.form.content = '';
            }
        }
    }
</script>

<style scoped>
#InsertPosts{
    margin: 30px;
}
</style>

// frontend-react/src/components/InsertPosts.js
import React, {Component} from "react";
import axios from 'axios';

class InsertPosts extends Component {

    constructor(props) {
        super(props);
        this.handleChange = this.handleChange.bind(this);
        this.handleSubmit = this.handleSubmit.bind(this);
    }

    state = {
        title: '',
        author: '',
        content: '',
    };

    handleChange = event => {
        this.setState({
            [event.target.name]: event.target.value
        });
    };

    handleSubmit = event => {
        event.preventDefault();
        console.log(this);
        const posts = {
            title: this.state.title,
            author: this.state.author,
            content: this.state.content,
        };

        console.log(JSON.stringify(posts));
        axios.post('/api/insert', JSON.stringify(posts),
            {headers: {'Content-Type': 'application/json;charset=UTF-8'}}
        ).then(response => {
            console.log(response);
        })
    };

    render() {
        return (
            <div>
                <form onSubmit={this.handleSubmit}>
                    <label>
                        title :
                        <input
                            type="text"
                            placeholder="타이틀"
                            name="title"
                            value={this.state.title}
                            onChange={this.handleChange}/>
                        author:
                        <input type="text"
                               name="author"
                               placeholder="작가"
                               value={this.state.author}
                               onChange={this.handleChange} />
                        content :
                        <input type="text"
                               placeholder="내용"
                               name="content"
                               value={this.state.content}
                               onChange={this.handleChange}/>
                    </label>
                    <button type="submit">등록</button>
                </form>
            </div>
        );
    }
}

export default InsertPosts;
