// frontend-react/src/components/List.js
import React, {Component} from "react";
import axios from 'axios';

class List extends Component {

    constructor(props){
        super(props);
        this.state = {
            postLists: []
        }
    }

    async componentDidMount(){
        await axios.get('/api/list')
            .then(res => {
                const postLists = res.data;
                this.setState({ postLists });
            });
    }


    render() {
        const {postLists} = this.state;

        if (postLists.length > 0) {
            return postLists.map(post => {
                return (
                    <div key={post.id}>
                        <p>title : {post.title}</p>
                        <p>author : {post.author}</p>
                    </div>
                );
            });
        } else {
            return <h3>No Photos</h3>;
        }
    }
}

export default List;

// frontend/src/views/List.vue
<template>
    <div>
        <h1>{{ msg }}</h1>
        <b-table striped hover :items="posts"></b-table>
        <Posts></Posts>
        <p v-for="post in posts" :key="post.id">{{post.author}} : {{post.content}} : {{post.title}}</p>
    </div>
</template>

<script>
    import Posts from  '@/components/PostsSave'

    export default {
        name: "List",
        components: {
            Posts
        },
        data(){
            return {
                msg : 'BackEnd API call',
                posts: []
            }
        },
        created(){
            this.$http.get('/api/list').then((resp=>{
                this.posts = resp.data;
            }));
        }
    }
</script>

<style scoped>

</style>
